config/routes.rb
Rails.application.routes.draw do

  root 'keys#index'
  get 'request', to: 'request#index'
  get 'request/index'
  get 'find_duplicates', to: 'request#find_duplicates'

  resources :keys
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/key.rb
class Key < ApplicationRecord
    validates :correo, presence: true, email_format: { message: "Doesn't look like an email address" } ,uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/keys_controller.rb
class KeysController < ApplicationController
  before_action :set_key, only: [:show, :edit, :update, :destroy]

  # GET /keys
  # GET /keys.json
  def index
    @keys = Key.all
    @key = Key.new
  end

  # GET /keys/1
  # GET /keys/1.json
  def show
  end

  # GET /keys/new
  def new
    @key = Key.new
  end

  # GET /keys/1/edit
  def edit
  end

  # POST /keys
  # POST /keys.json
  def create
    @key = Key.new(key_params)
    @key.correo = @key.correo.strip;
    @key.api_key = Digest::MD5.hexdigest(@key.correo)
    @key.cantidadReq = 0
    respond_to do |format|
      if @key.save        
        format.js
      else        
        format.js
      end
    end
  end

  # PATCH/PUT /keys/1
  # PATCH/PUT /keys/1.json
  def update
    respond_to do |format|
      if @key.update(key_params)
        format.html { redirect_to @key, notice: 'Key was successfully updated.' }
        format.json { render :show, status: :ok, location: @key }
      else
        format.html { render :edit }
        format.json { render json: @key.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keys/1
  # DELETE /keys/1.json
  def destroy
    @key.destroy
    respond_to do |format|
      format.html { redirect_to keys_url, notice: 'Key was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_key
      @key = Key.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def key_params
      params.require(:key).permit(:correo, :api_key, :cantidadReq)
    end
end

app/controllers/request_controller.rb
class RequestController < ApplicationController
  def index
  end

  def find_duplicates
      dataD = params[:data]
      data =Array.new
      dataD.each do |word|
        data.push(word.strip)
      end
      api_key = params[:api_key]
      unless data.nil? || api_key.nil?
        key = Key.find_by(api_key: api_key)
        unless key.nil?
          key.update(cantidadReq: key.cantidadReq+1)
          dataIndex = {}
          duplicates = []
          data.each_with_index do |value, indx|
            index_key = value
            index_value = indx
            if !dataIndex.has_key?(index_key)
              dataIndex.store(index_key, [])
            end
            dataIndex[index_key].push(index_value)
          end
          dataIndex.each do |key, indxs|
            if indxs.count > 1
              duplicates.push({word: key,positions: indxs})
            end
          end
          response = {status:"success", code:200, duplicates:duplicates}
          render json:  response, status: :ok
        else
          response = {status:"unauthorized", code:401}
          render json:  response, status: :ok
        end
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/keys_helper.rb
module KeysHelper
end

app/helpers/request_helper.rb
module RequestHelper
end

app/views/keys/_form.html.erb
<%= form_for(key,remote:true) do |f| %>
  <% if key.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(key.errors.count, "error") %> prohibited this key from being saved:</h2>

      <ul>
      <% key.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class=>
    <div class="field form-group">
      <%= f.label :correo %>
      <div class="row">
        <div class="col-md-8">
            <%= f.text_field :correo %>
        </div>
        <div class="col-md-4 actions">
          <%= f.button :submit=>"Generar API Key", class:'btn btn-success'  %>
        </div>
    </div>
    <span id="errorCorreo" class="text-danger"></span>
  </div>
<% end %>

app/views/keys/_new.html.erb
<hr/>
<%= render 'form', key: @key %>
<hr/>

app/views/keys/create.js.erb
function updateTable(){
    $.get("/keys.json",function(result) {
        $('#tablaKeys').bootstrapTable("load",result);
    });
}
<% if @key.errors.count == 0 %>
    $('#errorCorreo').html("");
    $('#key_correo').val("");
    iziToast.success({
        title: 'OK',
        message: 'Api key generada Exitosamente',
    });
    updateTable();

<% else %>
    
    $('#errorCorreo').html("<%= @key.errors.full_messages.first %> ")
    iziToast.error({
    title: 'Error',
    message: 'No se pudo generar una nueva Api Key',
    });
<% end %>

app/views/keys/edit.html.erb
<h1>Editing Key</h1>

<%= render 'form', key: @key %>

<%= link_to 'Show', @key %> |
<%= link_to 'Back', keys_path %>

app/views/keys/index.html.erb
<% provide(:admin, 'active') %>
<% provide(:request, '') %>
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>API Keys</h1>
  <%= render 'new', key: @key %>

  <table id="tablaKeys"
        class="sortable table-bordered" 
        data-toolbar="#toolbar"
        data-search="true"
        data-pagination="true" 
        data-minimum-count-columns="2"  
        data-id-field="Id"
        data-unique-id="Id"
        data-page-size="10"
        data-show-footer="false">
    <thead>
        <tr>
          <th  data-sortable="true" data-field="correo">Correo</th>
          <th  data-field="api_key">Api key</th>
          <th  data-sortable="true" data-field="cantidadReq">Cantidad Req</th>
        </tr>
    </thead>
    <tbody>
      <% @keys.each do |key| %>
        <tr>
          <td><%= key.correo %></td>
          <td><%= key.api_key %></td>
          <td><%= key.cantidadReq %></td>
        </tr>
      <% end %>    
    </tbody>
  </table>
</div>

<%= javascript_include_tag "keysIns" %>

app/views/keys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Correo:</strong>
  <%= @key.correo %>
</p>

<p>
  <strong>Api key:</strong>
  <%= @key.api_key %>
</p>

<p>
  <strong>Cantidadreq:</strong>
  <%= @key.cantidadReq %>
</p>

<%= link_to 'Edit', edit_key_path(@key) %> |
<%= link_to 'Back', keys_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiKeyGenerator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default ">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="">Find duplicates</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="<%= yield(:admin) %>"><a href="/">Admin <span class="sr-only">(current)</span></a></li>
          <li class="<%= yield(:request) %>"><a href="/request">Request</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
    <%= yield %>
  </body>
</html>

app/views/request/index.html.erb
<% provide(:admin, '') %>
<% provide(:request, 'active') %>

<div class="container">
    <div class="row">
        <div class="col-md-8">
        <h3>Prueba Request</h3>
        <hr/>
            <form>
                <div class="form-group">
                    <label for="apiKey">Su API Key aquí</label>
                    <input type="text" id="apiKey" name="apiKey" class="form-control"></input>
                    <span id="errorApiKey" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label for="data">Palabras</label>
                    <input type="text" id="data" name="data" class="form-control"></input>
                    <small id="dataHelp" class="form-text text-muted">Digite las palabras separadas por una coma y sin espacios.</small>
                    <small id="dataHelp" class="form-text text-muted">Por ejemplo: hola,parso,mundo,hola,agua,papa,parso</small>
                    <br/>
                    <span id="errorData" class="text-danger"></span>
                </div>
            </form>
            <button class="btn btn-warning" id="btnSend" onclick="sendRequest()">Send Request</button>
            <button class="btn btn-info" id="btnSend" onclick="limpiar()">Limpiar</button>
        </div>
        <div class="col-md-4" id="respuestaDiv">
            <h3>Respuesta</h3>
            <hr/>
            <div id="respuesta">
            </div>
        </div>
    </div>
</div>

<%= javascript_include_tag "requestIns" %>